# rdd13r on 2024-08-12

name: Lugaru CI

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle Wrapper
        run: ./gradle build

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4

# References:
#
#   General on Workflows:
# - https://docs.github.com/en/actions
# - https://github.com/actions
#
#   This workflow uses the following GitHub-hosted runners:
# - https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
# - https://github.com/gradle/actions
#
#   Marketplace:
# - https://github.com/marketplace?type=actions